### ISSUE TITLE
Initial database schema

### ISSUE THREAD

**Issue by Matsuuu** [Shy-Boys-Club/dotties#10]
I think we have initially need for 3 tables: Users and Repositories, Images

Users:

| Type | Name |
|---|---|
| PK int | ID |
| VARCHAR | Github Username | 
| VARCHAR | Github access token |
| VARCHAR | Github refresh token | (if we do actually need this)
| VARCHAR | Email |

Repositories

| Type | Name |
|---|---|
| PK int | ID |
| FK(User) int |  User ID | 
| VARCHAR | Repository name | ( We could concat the whole name here e.g. "Shy-Boys-Club/dotfiles" to save time on lookup )
| LONGTEXT | Description |
| long | Score |

Images

| Type | Name |
|---|---|
| PK int | ID |
| FK(Repository) int |  Repository ID | 
| VARCHAR | Image URL |

Later on we could maybe set up a Comments table ?

**Comment by Sam-Lane** [comment]
I think this is a good start to get an mvp out

**Comment by Matsuuu** [comment]
This has been implemented in the ORM patch
